server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false  #自我保护机制
  instance:
    hostname: peer1
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer2:8769/eureka/
