server:
  port: 8769
eureka:
  server:
    enable-self-preservation: false  #自我保护机制
  instance:
    hostname: peer2
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer1:8761/eureka/